# Generated by Django 4.1.1 on 2022-10-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country', models.TextField(max_length=100)),
                ('nationality', models.TextField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=45)),
                ('role_of_experience', models.TextField(max_length=120)),
                ('resumee', models.FileField(upload_to='')),
            ],
        ),
    ]
