# Generated by Django 4.1.1 on 2022-10-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='resumee',
            field=models.ImageField(upload_to='Applicants/resumee/'),
        ),
    ]
