# Generated by Django 4.1.1 on 2022-10-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_applicants_resumee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='resumee',
        ),
    ]
